### ISSUE TITLE
Need to load Node Env Vars

### ISSUE THREAD

**Issue by grant** [anon-dot-com/examples#1]
This file doesn't currently load env vars, making the demo fail.

`demo/examples/runtime-sdk-typescript/index.ts`

```
import 'dotenv/config';

console.log("process.env")
console.log(process.env)
```

**Comment by jeffreyyun** [comment]
fixed with https://github.com/anon-dot-com/examples/commit/e35e524f468ce90c4a69992b360abff603e0f260
